name: Release Extension

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run unit tests
      run: npm run test:unit
      
    - name: Run integration tests
      run: npm run test:integration
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      
    - name: Run E2E tests
      run: npm run test:e2e
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        
    - name: Validate Cloudflare API connectivity
      run: |
        if [ -z "$CLOUDFLARE_API_TOKEN" ]; then
          echo "❌ CLOUDFLARE_API_TOKEN is not set"
          exit 1
        fi
        
        echo "🔍 Testing Cloudflare API connectivity..."
        
        # Test API endpoint with a valid Radar endpoint
        response=$(curl -s -w "%{http_code}" -o /tmp/api_response.json \
          -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
          -H "Accept: application/json" \
          "https://api.cloudflare.com/client/v4/radar/ranking/top")
        
        http_code="${response: -3}"
        
        if [ "$http_code" = "200" ]; then
          echo "✅ Cloudflare API is accessible and responding correctly"
          echo "📊 API Response sample:"
          head -c 200 /tmp/api_response.json
          echo ""
        else
          echo "❌ Cloudflare API returned HTTP $http_code"
          echo "📄 Response:"
          cat /tmp/api_response.json
          exit 1
        fi
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

  release:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Create Chrome extension package
      run: |
        cd extension
        zip -r ../akamai-asn-details-chrome.zip . -x "*.xpi" "*.zip"
        
    - name: Create Firefox extension package
      run: |
        cd extension
        # Install web-ext with specific version to avoid Node.js compatibility issues
        npm install -g web-ext@7.8.0
        
        # Build Firefox XPI directly without config file
        web-ext build --source-dir . --artifacts-dir ../ --filename akamai-asn-details-firefox.xpi
        
    - name: Verify build artifacts
      run: |
        echo "Verifying build artifacts..."
        ls -la *.zip *.xpi
        echo "File sizes:"
        du -h *.zip *.xpi
        
        if [ ! -f "akamai-asn-details-chrome.zip" ]; then
          echo "❌ Chrome extension package not found!"
          exit 1
        fi
        
        if [ ! -f "akamai-asn-details-firefox.xpi" ]; then
          echo "❌ Firefox extension package not found!"
          exit 1
        fi
        
        echo "✅ All build artifacts verified"
        
    - name: Check if release exists
      id: check_release
      run: |
        TAG_NAME=${GITHUB_REF#refs/tags/}
        echo "Checking for existing release with tag: $TAG_NAME"
        
        if gh release view "$TAG_NAME" >/dev/null 2>&1; then
          echo "exists=true" >> $GITHUB_OUTPUT
          echo "Release $TAG_NAME already exists"
        else
          echo "exists=false" >> $GITHUB_OUTPUT
          echo "No existing release found for tag $TAG_NAME"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Delete existing release
      if: steps.check_release.outputs.exists == 'true'
      run: |
        TAG_NAME=${GITHUB_REF#refs/tags/}
        echo "Deleting existing release: $TAG_NAME"
        gh release delete "$TAG_NAME" --yes
        echo "✅ Successfully deleted existing release"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          akamai-asn-details-chrome.zip
          akamai-asn-details-firefox.xpi
        generate_release_notes: true
        draft: false
        prerelease: false
        fail_on_unmatched_files: false
        make_latest: true
        body: |
          ## Release ${{ github.ref_name }}
          
          This release includes:
          - Chrome extension package (akamai-asn-details-chrome.zip)
          - Firefox extension package (akamai-asn-details-firefox.xpi)
          
          ### Installation
          - **Chrome**: Download the .zip file and load as unpacked extension
          - **Firefox**: Download the .xpi file and install as temporary add-on
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Verify release creation
      run: |
        TAG_NAME=${GITHUB_REF#refs/tags/}
        echo "Verifying release creation for tag: $TAG_NAME"
        
        if gh release view "$TAG_NAME" >/dev/null 2>&1; then
          echo "✅ Release $TAG_NAME created successfully"
          gh release view "$TAG_NAME" --json name,url,assets
        else
          echo "❌ Failed to create release $TAG_NAME"
          exit 1
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
